feat(English): Translate lib/common in English

diff --git a/lib/common b/lib/common
--- a/lib/common
+++ b/lib/common
@@ -4,98 +4,98 @@
 ## VARIABLES
 ###
 
-GRAS="\033[1m"                      # GRAS
-COULEUR_ROUGE="\033[31m"            # Couleur rouge
-COULEUR_VERT="\033[32m"             # Couleur vert
-COULEUR_BLEU="\033[34m"             # Couleur bleu
-COULEUR_JAUNE="\033[1;33m"          # Couleur jaune
+BOLD="\033[1m"
+RED_COLOR="\033[31m"
+GREEN_COLOR="\033[32m"
+BLUE_COLOR="\033[34m"
+YELLOW_COLOR="\033[1;33m"
 
-COULEUR_DEFAUT="\033[0m"            # Annulation de couleur
-COULEUR_INFO="\033[7;49;34m"        # Fond bleu
-COULEUR_SUCCES="\033[7;49;32m"      # Fond vert
-COULEUR_ATTENTION="\033[7;49;33m"   # Fond jaune/orange
-COULEUR_ERREUR="\033[7;49;31m"      # Fond rouge
-COULEUR_SPECIALE="\033[1;49;34m"    # Écriture grasse, bleue avec fond normal
+DEFAULT_COLOR="\033[0m"          # Reset color
+INFO_COLOR="\033[7;49;34m"       # Blue background
+SUCCESS_COLOR="\033[7;49;32m"    # Green background
+WARNING_COLOR="\033[7;49;33m"    # Yellow/orange background
+ERROR_COLOR="\033[7;49;31m"      # Red background
+SPECIAL_COLOR="\033[1;49;34m"    # Bold blue writing with normal background
 
 #####
-## FONCTIONS
+## FUNCTIONS
 ###
 
-# Messages avec des couleurs, comme les arc-en-ciel :-)
+# Messages with colors, like rainbows :-)
 # Cf. https://misc.flogisoft.com/bash/tip_colors_and_formatting
-msg_couleur() {
-  # $1: couleur choisie
-  # $2: titre
-  # $3: message
-  echo -e "${1}[${2}]${COULEUR_DEFAUT} ${3}" 1>&2
+colored_msg() {
+  # 1: choosen color
+  # 2: title
+  # 3: message
+  echo -e "${1}[${2}]${DEFAULT_COLOR} ${3}" 1>&2
 }
-# Message normal
+# Default message
 msg() {
-  echo -e "${COULEUR_DEFAUT}${1}" 1>&2
+  echo -e "${DEFAULT_COLOR}${1}" 1>&2
 }
-# Message spécial
-msg_special() {
-  echo -e "${COULEUR_SPECIALE}${1}${COULEUR_DEFAUT}" 1>&2
+# Special message
+special_msg() {
+  echo -e "${SPECIAL_COLOR}${1}${DEFAULT_COLOR}" 1>&2
 }
-# Message d'information, plus prononcé
-msg_info() {
-  msg_couleur "${COULEUR_INFO}" "INF" "${1}"
+# Message of information, more visible
+info_msg() {
+  colored_msg "${INFO_COLOR}" "INFO" "${1}"
 }
-# Porter l'attention sur une information importante
-msg_attention() {
-  msg_couleur "${COULEUR_ATTENTION}" "ATT" "${1}"
+# Focus on important information
+warning_msg() {
+  colored_msg "${WARNING_COLOR}" "WARN" "${1}"
 }
-# Erreur ç_ç
-msg_erreur() {
-  msg_couleur "${COULEUR_ERREUR}" "ERR" "${1}"
+# Error ç_ç
+error_msg() {
+  colored_msg "${ERROR_COLOR}" "ERR " "${1}"
 }
-# Réussite !
-msg_succes() {
-  msg_couleur "${COULEUR_SUCCES}" "OK " "${1}"
+# Success !
+success_msg() {
+  colored_msg "${SUCCESS_COLOR}" " OK " "${1}"
 }
-# Échec, j'arrête le programme !
-msg_erreur_exit() {
-  msg_erreur "${1}" && exit 1
+# Fail, I'm out of the program!
+err_msg_and_exit() {
+  error_msg "${1}" && exit 1
 }
-# Message pour DEBUG en temps de développement
-msg_debug() {
+# DEBUG messages for development periods
+debug_msg() {
   if [[ ${DEBUG} == true ]]; then
     msg "$1"
   fi
 }
 
-# Vérification de la présence d'un programme dans le système
-# argument 1 : variable d'export qui définit le chemin du programme à utiliser
-# argument 2 : nom exact du programme
-test_commande_presente() {
-  message="Commande '$2' non trouvée !"
-  # préparation de la commande qui sera lancée
-  contenu_export=`which $2` || return 1
+# Check program exist in system
+# 1: name for export variable which value is program path to use
+# 2: program exact name
+check_command_isavailable() {
+  message="'$2' command not found!"
+  # prepare command to be executed
+  variable_value=`which $2` || return 1
 
-  # vérification de la présence de notre commande
+  # check command availability
   if test -n $(command -v $2 &> /dev/null); then
-    export $1="${contenu_export}"
+    export $1="${variable_value}"
     return 0
   fi
   return 1
 }
 
-# Exécute le script donné en paramètre, si le fichier existe
-# 1: Script à exécuter
-# 2: (optionnel) Message pre-exécution
-# 3: (optionnel) Message post-exécution
-executer_script() {
-  # Aucune action si le fichier n'existe pas
+# Execute script given in parameter 1. If this one exists.
+# 1: to be executed script
+# 2: (optional) pre-execution message
+# 3: (optional) post-execution message
+script_exec() {
+  # If file doesn't existe: do nothing
   if [[ -f "${1}" ]]; then
-    # Message pre-exécution
+    # pre-execution message
     if [[ -n "${2}" ]]; then
-      msg_info "${2}"
+      info_msg "${2}"
     fi
-    # Exécution
+    # execution
     source "${1}"
-    # Message post-exécution
+    # post-execution message
     if [[ -n "${3}" ]]; then
-      msg_info "${3}"
+      info_msg "${3}"
     fi
   fi
 }
